burden_web/config/routes.rb
BurdenWeb::Engine.routes.draw do
  resources :tasks, path: '/', only: [:index], constraints: { id: /[a-z0-9_:]+/ } do
    member{ get :run }
    resources :runs, only: [:index, :show]
  end
end

burden_web/app/controllers/burden_web/application_controller.rb
module BurdenWeb
  class ApplicationController < ActionController::Base
    def rake_tasks
      @rake_tasks ||= begin
        Rails.application.load_tasks
        Rake.application.tasks.keep_if do |task|
          task.name =~ /^[a-z0-9_:]+$/
        end
      end
    end
  end
end

burden_web/app/controllers/burden_web/runs_controller.rb
module BurdenWeb
  class RunsController < ApplicationController
    def index
      @runs = Burden.runs.history(params[:task_id])
    end
  end
end

burden_web/app/controllers/burden_web/tasks_controller.rb
module BurdenWeb
  class TasksController < ApplicationController
    def index
      @tasks = Burden.runs.summary
      (rake_tasks.map(&:name) - @tasks.map(&:name)).each do |nr_task| # Never runned tasks
        next if ignore? nr_task
        @tasks << Burden.runs.new(
          name: nr_task
        )
      end
    end

    def ignore? name
      Burden.config.ignored_tasks.collect{ |r| (name =~ r) ? 1 : 0 }.map(&:to_i).inject(:+) != 0
    end

    def run
      Rails.application.load_tasks
      task = Rake::Task[params[:id]]

      task.prerequisite_tasks.each{ |t| t.execute(nil) }
      task.execute(nil)
    rescue => e # Gotta catch 'em all!
    ensure
      redirect_to params[:back]
    end
  end
end

burden_web/app/helpers/burden_web/application_helper.rb
module BurdenWeb
  module ApplicationHelper
    def task_label run
      case run.success
      when true
        'success'
      when false
        'alert'
      else
        'secondary'
      end
    end
  end
end

burden_web/app/views/burden_web/runs/index.html.erb
<%= link_to '&larr; Back'.html_safe, tasks_path, class: 'small radius secondary button' %>
<%= link_to 'Run', run_task_path(params[:task_id], back: task_runs_path(params[:task_id])), class: 'small radius button' %>
<br><br>
<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Timestamp</th>
      <th>Took</th>
    </tr>
  </thead>
  <tbody>
    <% @runs.each do |run| %>
    <tr>
      <td><span class="<%= task_label(run) %> radius label"><%= run.name %></span></td>
      <td><%= l run.timestamp, format: :short %> (<%= time_ago_in_words(run.timestamp) %> ago)</td>
      <td><%= run.execution_time.round(6) %>s</td>
    </tr>
    <% end %>
  </tbody>
</table>

burden_web/app/views/burden_web/tasks/index.html.erb
<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Last Run</th>
      <th>Took</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |run| %>
    <tr>
      <td><span class="<%= task_label(run) %> radius label"><%= run.name %></span></td>
      <% if run.timestamp %>
        <td><%= time_ago_in_words(run.timestamp) %> ago</td>
        <td><%= run.execution_time.round(6) %>s</td>
        <td><%= link_to 'Run', run_task_path(run.name, back: tasks_path), class: 'small radius button' %></td>
        <td><%= link_to 'History', task_runs_path(run.name), class: 'secondary small radius button' %></td>
      <% else %>
        <td>never</td>
        <td>&mdash;</td>
        <td><%= link_to 'Run', run_task_path(run.name, back: tasks_path), class: 'small radius button' %></td>
        <td><a class="disabled secondary small radius button">History</a></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

burden_web/app/views/layouts/burden_web/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Burden</title>
  <%= stylesheet_link_tag    'burden_web/application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <div class="large-12 columns">
      <h2 class="subheader">Burden Dashboard</h2>
      <%= yield %>
    </div>
  </div>
</body>
</html>